version: "3.8"

services:
  flask-cnn-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat-dog-classifier-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
      - MODEL_PATH=models/cats_vs_dogs_classifier
      - CLASSES_FILE=models/classes.txt
      - PYTHONPATH=/app
    volumes:
      # Mount models directory to easily update models without rebuilding
      - ./models:/app/models:ro
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:5000/health', timeout=10)"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - cnn-network
    # Resource limits to prevent container from consuming too much memory
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  cnn-network:
    driver: bridge

# Optional: Add volume for persistent model storage
volumes:
  model-data:
    driver: local
